### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/sim/'

### ISSUE THREAD

**Issue by Yanxing-Shi** [matwilso/domrand#1]
Hello, I'm sorry to bother you,  I have made these mistakes:
```
Traceback (most recent call last):
  File "run_domrand.py", line 5, in <module>
    from domrand.define_flags import FLAGS
  File "/home/user/xing/domrand/domrand/define_flags.py", line 67, in <module>
    data_files = os.listdir(data_path)
FileNotFoundError: [Errno 2] No such file or directory: './data/sim/'
```
And I have these mitstakes:
```
(gymlab) user@user:~/xing/domrand$ python3 run_domrand.py
Traceback (most recent call last):
  File "run_domrand.py", line 36, in <module>
    main()
  File "run_domrand.py", line 26, in main
    sim_manager = SimManager(filepath=FLAGS.xml, gpu_render=FLAGS.gpu_render, gui=FLAGS.gui, display_data=FLAGS.display_data)
  File "/home/user/xing/domrand/domrand/sim_manager.py", line 27, in __init__
    self.model = load_model_from_path(filepath)
  File "cymj.pyx", line 131, in mujoco_py.cymj.load_model_from_path
Exception: Failed to load XML file: assets/xmls/kuka/lbr4_reflex.xml. mj_loadXML error: b'XML parse error at line 0, column 0:\nFailed to open file\n'
```

**Comment by matwilso** [comment]
Sorry I did not see this issue until very recently.

For the first mistake, this is because you have not made a folder called sim on your file system.  On linux, this would be fixed with the commands below.  You could also add an `os.makedirs` to the code so that it generates those folders if they don't exist.

```
mkdir data
mkdir data/sim
```

For the second mistake, that had to do with the variable pointing to the wrong path in `define_flags.py`.  I fixed that in the latest commit, so you should be able to pull that.
